name: Build and Push on PRs

on:
  pull_request:
    branches: [ main, develop ]

env:
  ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
  ECR_REPOSITORY: naturescot/trap-registration
  TR_PORT: 3000
  TR_PATH_PREFIX: trap-registration
  TR_SESSION_SECRET: override_this_value
  TR_API_URL: override_this_value

jobs:

  build:
    name: Build the Image
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install all the pre-requisites
      run: npm ci && npm prune --production

    - name: Check the pre-start operations
      run: npm run prestart

    - name: Configure AWS Configuration
      run: |
        mkdir -p ~/.aws
        echo [default] > ~/.aws/config
        echo region = eu-west-2 >> ~/.aws/config
        echo output = json >> ~/.aws/config

    - name: Configure AWS Credentials
      run: |
        mkdir -p ~/.aws
        echo [default] > ~/.aws/credentials
        echo aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }} >> ~/.aws/credentials
        echo aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> ~/.aws/credentials

    - name: Login to Amazon ECR
      run: $(aws ecr get-login --no-include-email)

    - name: Build and tag the Docker Image
      run: docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA} .

    - name: Push the Docker Image to Amazon ECR
      run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA}

    - name: Logout of Amazon ECR
      if: always()
      run: docker logout $ECR_REGISTRY
